### ISSUE TITLE
Video and repo doesn't works

### ISSUE THREAD

**Issue by MrTheBarbarian** [robwebset/screensaver.video#10]
Hi! I have an interest of this great project. I would like to fork it, but the video links and pictures doesn't work. Can I have get it some how?

**Comment by robwebset** [comment]
I just had a look, I can't find them anywhere on my machine. I think I origianally got most of them from youtube - so you should be able to download then from there.

If you are interested I can transfer the project to you (rather than you fork it) - It would make you the new official owner :)

**Comment by MrTheBarbarian** [comment]
Yes! I'm interested of this project, but unfortunately, my programmer skills and knowledge are not enough to manage the project for now. Actually I have small part of the videos, but not All. If this add-on not working on version 18, I'm not sure that I can made it compatible.  
Thank you for your answer.
