### ISSUE TITLE
Great Screensaver but on my system it fails when I try to add a .STRM file

### ISSUE THREAD

**Issue by ab1976** [robwebset/screensaver.video#2]
on my system it fails when I try to add a .STRM file as video (myIPCAM Stream)

Is it possible to add a Stream to the screensaver????

**Comment by robwebset** [comment]
Hi @ab1976 

Never tried anything with STRM files, so 2 things would be a good hlep
1) Does the STRM file you are trying it you just try and play it in Kodi (i.e. outside the screensaver)
2) Do you have a link to a sample STRM file that I copuld user to test things with?

Thanks
Rob

**Comment by robwebset** [comment]
OK, I've done some checking about STRM files, it appears they are just a file pointing to another file - so tried pointing it to a file on my local hard drive and then selecting the strm file for the screensaver and everything appears to work OK.

Please can you supply some more infor for your situation.

Thanks
Rob

**Comment by ab1976** [comment]
If I select my .strm file and select review I get a blank screen for a second and then returns to the config screen

**Comment by ab1976** [comment]
BTW, if I select my strm file as a video it plays just fine.

**Comment by robwebset** [comment]
Please can you enable logging in the VideoScreensaver settings and the System wide debug and post it somewhere so I can see if that gives any clues.

https://github.com/robwebset/screensaver.video/wiki#Debugging

Thanks
Rob

**Comment by ab1976** [comment]
https://dl.dropboxusercontent.com/u/86134667/Logs/kodi.log 

And the URL I use in my strm points to FOSCAM IPCAM and looks like

rtsp://user:password@192.168.1.x:88/videoSub

I can simply play it from Video's

Thanks for looking into this

**Comment by robwebset** [comment]
Thanks for the log, from the message printed, VideoScreensaver thinks that ther eis already some kind of Media playing - so will not start the video. Do you have some form of background media playing? (Kodi thinks you have)

Can you try disabling the VideoScreensaver setting: "Prevent Screensaver Starting If Playing Media" and seeing what it does.

https://github.com/robwebset/screensaver.video/wiki#Configuration

Thanks
Rob

**Comment by ab1976** [comment]
Thanks for looking into this, it was indeed a media which played on the background. 

I was testing your screensaver on a test unit, which had some other tests running on the background..

It now works perfectly, when I m not using the mediaplayer it automatically opens the security camera :-)

Thanks again.

**Comment by robwebset** [comment]
Glad you got it working
