### ISSUE TITLE
Images for screensaver.tvtunes

### ISSUE THREAD

**Issue by latts9923** [robwebset/screensaver.video#9]
Hello,

I was looking at the TvTunes Screensaver and the Wiki page is missing a few images. I was wondering if you still have those available.  They were linked to https://github.com/robwebset/repository.robwebset/raw/master/screensaver.tvtunes/images/. The images are...

TvTunes-Screensaver-Slider.JPG
TvTunes-Screensaver-Crossfade.JPG
TvTunes-Screensaver-Tabledrop.JPG
TvTunes-Screensaver-Starwars.JPG
TvTunes-Screensaver-RandomZoomIn.JPG
TvTunes-Screensaver-AppleTVLike.JPG
TvTunes-Screensaver-GridSwitch.JPG

Thanks! Jeff

**Comment by robwebset** [comment]
I'm afraid not - I have taken a look around and can't find anything - it looks like they are just samples of what the screensavers look like - so you might be able to reproduce them by starting up the screensaver in each mode
